FROM node:10
WORKDIR /usr/
RUN git clone https://github.com/EvolutionSoftware12/Prog_Calc.git
RUN npm install -g ionic
RUN npm install 
RUN apt-get update
RUN apt install -y github



EXPOSE 3000