FROM node:10
WORKDIR /usr/

RUN npm install -g ionic
RUN npm install 
RUN apt-get update
RUN apt install -y github
RUN git clone https://github.com/EvolutionSoftware12/Prog_Calc.git


EXPOSE 3000
